version: '3.8'
services:
  db:
    container_name: like_a_mozart_postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: like_a_mozart_development
      POSTGRES_USER: like_a_mozart
      POSTGRES_PASSWORD: like_a_mozart
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
